targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/model/**.dart
        options:
          build_extensions:
            '^lib/model/{{}}.dart': 'lib/model/generated/{{}}.g.dart'
      freezed|freezed:
        enabled: true
        options:
          build_extensions:
            '^lib/model/{{}}.dart': 'lib/model/generated/{{}}.freezed.dart'